### ISSUE TITLE
Create lambda function that returns weather and lightning data within specified time window

### ISSUE THREAD

**Issue by nightduck** [nightduck/stormWatch#26]
Triggered by an API Gateway call set as REST call. Give @HanyangLiu the link for this call when finished, so he can replace [update_url](https://github.com/nightduck/stormWatch/blob/ee25f5067f69b9e9dbc512c350e45d4cc02a6342/webpage/static/map.js#L14) in his D3 code.

**Comment by jingwennn** [comment]
Return the latest data

**Comment by nightduck** [comment]
This is now top priority. I'll find a way to generate simulated lightning data in the database. Focus on adding it to the returned data. Also, work with @HanyangLiu  (issue #30) for how to take in two timestamp arguments, and return lightning data in that window, and node data from the end of that window.

**Comment by nightduck** [comment]
Line below:

    cur.execute("select longitude, latitude, power, timestamp from stormwatch.lightning_readings \
    where timestamp>=%s and timestamp<=%s",(lightning_start_time, lightning_end_time))

Pulls from the wrong table. lightning_readings is pre-processed observations. You want post-processed data in lightning_strikes

**Comment by jingwennn** [comment]
Pass parameters "timestamp1" and "timestamp2" from API to Lambda

**Comment by nightduck** [comment]
Change sql condition on lines 10-11 to:

    select longitude, latitude, temp, pressure, humidity, rainfall, wind_direction, wind_speed, max(timestamp),
            battery, nodename from stormwatch.weather_readings
            where timestamp <= %s group by nodename;

Otherwise, if timestamp is too high, it might not return any data, and if too low, it may return more than 1 record per node. Additionally, nodenames should not be hardcoded in lambda function, if possible.

This new syntax returns 1 reading for each node in the table: the most recent reading prior to whatever %s is. This also works with an arbitrary number of nodes, so you don't have to hardcode the node names in the lambda function

**Comment by nightduck** [comment]
This
![image](https://user-images.githubusercontent.com/10158631/99922213-f5a7f680-2cf4-11eb-969c-58a003fdd9f1.png)

returns this:
![image](https://user-images.githubusercontent.com/10158631/99922245-30119380-2cf5-11eb-83f6-bae4c6d63db3.png)

**Comment by nightduck** [comment]
Just noticed the above is incorrect. Longitude and latitude are null for node 1, all data besides the timestamp is incorrect

**Comment by jingwennn** [comment]
<img width="1003" alt="Screen Shot 2020-12-03 at 2 16 20 PM" src="https://user-images.githubusercontent.com/44712783/101083135-26e4ba00-3572-11eb-8998-b3812bb03ccf.png">

**Comment by nightduck** [comment]
Found something better:

```
select temp, humidity, wind_direction, wind_speed, rainfall, nodename, latitude, longitude, max(timestamp), pressure, battery from
    (select
            temp, humidity, wind_direction, wind_speed, rainfall, nodename, latitude, longitude, timestamp, pressure, battery
            from weather_readings where timestamp <= '2020-12-01 11:45:34' and timestamp >= '2020-12-01 05:45:34'
    ) as t1
    group by nodename;
```

Returns:
![image](https://user-images.githubusercontent.com/10158631/101087238-927d5600-3577-11eb-8232-82f7b3e2811d.png)

**Comment by jingwennn** [comment]
Bug exists in the sql command.
<img width="1054" alt="Screen Shot 2020-12-09 at 10 31 46 PM" src="https://user-images.githubusercontent.com/44712783/101721785-60379100-3a6e-11eb-9b0e-680592643720.png">
