### ISSUE TITLE
Regularly poll for new data

### ISSUE THREAD

**Issue by nightduck** [nightduck/stormWatch#30]
Should poll for new data regularly. Work with jingwen on issue #26, as that REST call will provide you with the data you need

**Comment by nightduck** [comment]
New idea: only get the lightning strikes within a window and the most recent readings from nodes. Have a separate REST call to get historical weather data. This separate REST call would only be called when a chart is being displayed, which would cut down on unneccessary data usage.

**Comment by HanyangLiu** [comment]
Always get this error and new change in data does not get updated in the Chrome browser
"GET / HTTP/1.1" 304 -

**Comment by HanyangLiu** [comment]
> Always get this error and new change in data does not get updated in the Chrome browser
> "GET / HTTP/1.1" 304 -

temporally avoided by using Firefox

**Comment by nightduck** [comment]
It's not an error. It just means there's no new data since the last time you checked.

**Comment by nightduck** [comment]
You only call update() once

**Comment by HanyangLiu** [comment]
> It's not an error. It just means there's no new data since the last time you checked.

yeah but just don't know why Firefox does not have that issue

**Comment by HanyangLiu** [comment]
> You only call update() once

yeah I just realized that too
