### ISSUE TITLE
New lambda call to return historical sensor readings for a single node

### ISSUE THREAD

**Issue by nightduck** [nightduck/stormWatch#31]
Given a nodename and two timestamp IDs, return all sensor readings for that node in that time window. This will be used to generate historical graphs on the website (eg temp over the past day)

**Comment by jingwennn** [comment]
Pass parameters "timestamp1", "timestamp2", and "node" from API to Lambda

**Comment by nightduck** [comment]
I see no issue besides the hardcoded values, which I'm sure will be removed. @HanyangLiu when you're happy, close this issue
